"""add services table~

Revision ID: 08029e276033
Revises: e796e1a25514
Create Date: 2026-02-07 22:17:54.245553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08029e276033'
down_revision: Union[str, Sequence[str], None] = 'e796e1a25514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('preacher', sa.String(), nullable=True),
    sa.Column('leader', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_service_date'), 'services', ['service_date'], unique=False)
    op.create_unique_constraint(None, 'songs', ['hymn_number'])
    op.create_unique_constraint(None, 'songs', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_index(op.f('ix_services_service_date'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
