"""add service_time

Revision ID: 177313c788d7
Revises: d9a0b5071b92
Create Date: 2026-02-23 10:54:04.794091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177313c788d7'
down_revision: Union[str, Sequence[str], None] = 'd9a0b5071b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'service_time')
    # ### end Alembic commands ###
